debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Iae787e477b7eab1f11c79f30c35fd6808959e38a

Former-commit-id: e81b08b308bb2e9e68830273c29989430bc5a7c5
Former-commit-id: 55796dfa8510e4f59667d2e198a7c25c2d4660e1 [formerly 8993a00ecff54ee00c95f24df6cb71d4573ce5e9]
Former-commit-id: 8af52cc198096cf53aac7596091ccb21240a739c